< :hammer: >[(feat/run-script)/run-script] Update run script (#10)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,15 +1,71 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-if [[ $# -eq 1 && $1 -eq '-s' ]]; then
-    cargo run -p test --features safe
-    exit 0
+set -euo pipefail
+SHADERC_LIB="/usr/lib64/libshaderc_combined.a"
+install_shaderc()
+{
+    if [[ -r /etc/os-release ]]; then
+        # https://www.freedesktop.org/software/systemd/man/os-release.html
+        . /etc/os-release
+    else
+        echo "[ERROR] /etc/os-release not found or not readable"
+        exit 1
+    fi
+    case "${ID:-}" in
+        fedora)
+            sudo dnf install -y libshaderc-devel libshaderc-static
+            ;;
+        rhel|centos|rocky|almalinux)
+            sudo dnf install -y shaderc-devel
+            ;;
+        ubuntu|debian)
+            sudo apt-get update
+            sudo apt-get install -y libshaderc-dev
+            ;;
+        arch)
+            sudo pacman -Sy --needed shaderc
+            ;;
+        opensuse*|sles)
+            sudo zypper --non-interactive install shaderc shaderc-devel
+            ;;
+        *)
+            case "${ID_LIKE:-}" in
+                *rhel*|*fedora*)
+                    sudo dnf install -y shaderc-devel
+                    ;;
+                *debian*)
+                    sudo apt-get update
+                    sudo apt-get install -y libshaderc-dev
+                    ;;
+                *arch*)
+                    sudo pacman -Sy --needed shaderc
+                    ;;
+                *suse*)
+                    sudo zypper --non-interactive install shaderc shaderc-devel
+                    ;;
+                *)
+                    echo "[ERROR] OS unsupported: ID='${ID:-unknown}', ID_LIKE='${ID_LIKE:-unknown}'"
+                    exit 1
+                    ;;
+            esac
+            ;;
+    esac
+}
+
+run_cargo()
+{
+    export SHADERC_LIB_DIR="/usr/lib64"
+    exec cargo run -p test
+}
+
+if [[ "${1:-}" == "-s" ]]; then
+    exec cargo run -p test --features safe
 fi
 
-ls /usr/lib64/libshaderc_combined.a
-if [[ $? -eq 2 ]]; then
-    sudo dnf install libshaderc-devel libshaderc-static
+if [[ ! -f "$SHADERC_LIB" ]]; then
+    echo "[INFO] shaderc missing -> installing..."
+    install_shaderc
     cargo clean
-    SHADERC_LIB_DIR=/usr/lib64 cargo run
 fi
 
-cargo run -p test
+run_cargo
